Feature/fs 4
cookies-with-tea/movies-site pull request #14
Opened 2022-05-20 17:01 UTC by bookslomot

2022-05-21 17:25 UTC, s1veme requested changes

2022-05-21 17:25 UTC, s1veme commented on film/models.py
> +        from film.services import FilmRating
Почему здесь решил использовать отложенный импорт? Не думаешь, что лучше вынести импорт за функцию?

2022-05-21 17:25 UTC, s1veme commented on film/serializers.py
> +# Comment
Вот это лучше убрать.

2022-05-21 17:25 UTC, s1veme commented on film/services.py
> +        all_rating, k = 0, 0
Изменить название переменной `k`, также этот код вынести в отдельную функцию. Зачем создавать класс?

2022-05-21 17:33 UTC, bookslomot commented on film/models.py
> +        from film.services import FilmRating
Тогда будет вызван циклический импорт

2022-05-21 17:33 UTC, bookslomot commented on film/serializers.py
> +# Comment
так точно

2022-05-21 17:34 UTC, bookslomot commented on film/services.py
> +        all_rating, k = 0, 0
Думал, если еще что-то в фильмах буду делать, то понадобится, но ок

2022-05-23 12:41 UTC, bookslomot commented
Исправил код по flake8

2022-05-25 03:43 UTC, s1veme commented on noname/settings.py
>  DEBUG = True
`DEBUG` и `SECRET_KEY` надо вынести в переменные окружения.

2022-05-25 03:43 UTC, s1veme commented on noname/settings.py
> +SECRET_KEY = \
Убери здесь перенос, пусть будет так, как было.

2022-05-25 03:43 UTC, s1veme commented on noname/settings.py
> +        'django.contrib.'
Здесь тоже верни всё на место. Соединять так строчки - не самая лучшая идея.

2022-05-27 17:35 UTC, bookslomot commented on noname/settings.py
> +        'django.contrib.'
Убрал перенос там, где flask8 не мешал.

2023-10-22 01:21 UTC, closed without merging